#!/usr/bin/env sh

N=151
INDEX="index.sql"
SPRITE="sprite.sql"
DESCRIPTION="description.sql"
BALANCE="balance.sql"
EVOLUTION="evolution.sql"
ENCOUNTER="encounter.sql"
MOVES="moves.sql"

while getopts "n:" opt; do
	case $opt in
	n)
		N=${OPTARG}
	;;
	esac
done

index() {
	cat ${INDEX}
}

argparse() {
	echo ".parameter set @id ${2}
.output dist/${2}.html"
	echo "${1}"
}

concat_sql() {
	cat "${SPRITE}" "${DESCRIPTION}" "${BALANCE}" "${EVOLUTION}" "${ENCOUNTER}" "${MOVES}"
}

pokemon() {
	TMP_SQL=$(concat_sql)
	echo "${TMP_SQL}"
	i=1
	while [ "${i}" -le "${N}" ]; do
		argparse "${TMP_SQL}" ${i}
		i=$((i+1))
	done
}

main() {
	index
	pokemon
}

main
