#!/usr/bin/env bash

N=151
INDEX="index.sql"
SPRITE="sprite.sql"
DESCRIPTION="description.sql"
BALANCE="balance.sql"
EVOLUTION="evolution.sql"
ENCOUNTER="encounter.sql"
MOVES="moves.sql"

while getopts "n:" opt; do
	case $opt in
	n)
		N=${OPTARG}
	;;
	esac
done

function index() {
	cat ${INDEX}
}

function argparse() {
	echo ".parameter set @id ${2}
.output dist/${2}.html"
	echo "${1}"
}

function concat_sql() {
	cat "${SPRITE}" "${DESCRIPTION}" "${BALANCE}" "${EVOLUTION}" "${ENCOUNTER}" "${MOVES}"
}

function pokemon() {
	TMP_SQL=$(concat_sql)
	echo "${TMP_SQL}"
	for((i=1;i<=N;i++)); do
		argparse "${TMP_SQL}" ${i}
	done
}

function main() {
	index
	pokemon
}

main
